name: thehallway
favicon: null
layout_spectrum: 0.4779652557335794
typography_spectrum: 0.39274
title: The Hallway
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3d3d3d'
    - '#ffffff'
    - '#797979'
    - '#cccccc'
    - '#f43486'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
